### ISSUE TITLE
Focus replay on player when zoomed in

### ISSUE THREAD

**Issue by apazzolini** [pubgsh/client#12]
This should pan the map around keeping the focused player in the center of the screen.

Can also consider a toggle to zoom into the center of the bluezone instead of a player.

**Comment by eko24ive** [comment]
Hey @apazzolini may I try to make a PR for this feature?

**Comment by eko24ive** [comment]
Thanks for the greenlight - I'd be glad to help you! Really love the "mini-roadmap" you've described above.

I've actually tried to run client locally passing `https://api.pubg.sh` as a `REACT_APP_API` unfortunately it resulted with a '400' response from server with following body when I tried to find "myself":
```json
{"errors":[{"message":"Cannot query field \"teamSize\" on type \"PlayerMatch\".","locations":[{"line":15,"column":7}]}]}
```

So I thought that I have to set up local [api](https://github.com/pubgsh/api) as well. Having that done. I've run into the exact same error. (FYI: I've used my own PUBG_API_KEY and all I assume that every other .env variable was ok, since I got no errors when I launched API)

I decided to try one thing. Having a link to one of my matches on pubg.sh (https://pubg.sh/eko24/pc-eu/5ec8428f-edec-4e46-a235-8039e6507541) I decided to copy paste it into my local server, like this http://localhost:3001/eko24/pc-eu/5ec8428f-edec-4e46-a235-8039e6507541 and it throws at me another error: [screenshot](https://user-images.githubusercontent.com/25591824/44410623-83706680-a56d-11e8-92eb-64acc4b7e307.png). Here is content of that error:

```js
Uncaught (in promise) TypeError: Cannot read property 'name' of null
    at Telemetry.js:101
    at Map.withMutations (immutable.es.js:2245)
    at Telemetry.js:89
    at Array.forEach (<anonymous>)
    at Telemetry (Telemetry.js:36)
    at Match._callee$ (index.js:148)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:296)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3001/static/js/bundle.js:121505:21)
    at step (TimeSlider.js:39)
    at TimeSlider.js:39
```

I'd like to mention that I've been using `develop` branch since I saw it in some PR here and decided that this branch was made exclusively for development. I'd be really thankful if you'd help me figure out how I can get client up and running locally!

**Comment by apazzolini** [comment]
@eko24ive Hey dude, sorry if you went down a rabbit hole here. I was buys during the day and couldn't get to this until now. `develop` hadn't been touched in a long time and was definitely out of date. I've merged `master` into it, so it should be identical now.

Let me know if you have any other issues.

**Comment by eko24ive** [comment]
No problem at all! I'll try to get it running once again and let you know about results.

**Comment by eko24ive** [comment]
@apazzolini After I synced my forked repo with yours - everything just went smooth. But it looks like I've run into another issue.

On the map no matter which match I would pick to spectate (mine or some other player) it would always open and start at 05:24.6, zoomed in at some specific location and I'm unable to pan around the map until I put replay on pause. As soon as I hit "play" map is being scaled and moved to the position it was before and I'm again unable to navigate across the map: [GIF with issue](https://imgur.com/38aBPTF)

Also I saw this error in the console output. Not sure if it helps:
![image](https://user-images.githubusercontent.com/25591824/44460046-5b880e00-a614-11e8-93f6-115e67ba453c.png)

The same issue reproduces even if I switch to the local API. Do you have any thoughts why I'm facing this issue? Thanks in advance and sorry for making this hard for you.

**Comment by apazzolini** [comment]
@eko24ive No worries mate, these issues have been my fault.

The answer to your questions it to disable the dev tools in `Match/Options.js`.

**Comment by eko24ive** [comment]
Ok, let me try

**Comment by eko24ive** [comment]
Yeah, it worked! Honestly, I feel so stupid about it - I should've searched that timestamp or map parameters across the project 😂 

Anyway since it works, I'll start on the todo-list you've come up with (I think you might want to move it to the first issue-comment so we can get a nice progress bar on the issues page) and we'll see how it works out. Again, thank you so much for helping me get it right!

**Comment by apazzolini** [comment]
Tracked at #29.

**Comment by eko24ive** [comment]
Not any kind of a nitpick but maybe it's better to keep it under **In Progress** section since it is not really "done"?

**Comment by apazzolini** [comment]
Your pull request is under in progress, this issue is now redundant.

**Comment by eko24ive** [comment]
Got it
